version: '3.9'
services:
  nestapp:
    container_name: nestapp
    image: shahbazhrajaWeWork/nestapp:1.0.0
    build: .
    ports:
      - '3001:3001'
    environment:
      - DB_TYPE=postgres
      - PG_USER=admin
      - PG_PASSWORD=password
      - PG_DB=postgres
      - PG_PORT=5432
      - PG_HOST=db
      - SERVICE_NAME = ravenOps
      - PORT=3001
      - NODE_ENV = development
      - LOGGER_MIN_LEVEL = debug
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
