name: we-brokered deploy to EKS
on:
  push:
    branches: ['development']

jobs:
  LoginToAWS:
    runs-on: self-hosted

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

  buildImage-and-Push-to-ECR:
    runs-on: self-hosted
    needs: LoginToAWS

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Login to  AWS ECR
        uses: docker/login-action@v3
        with:
          registry: 767397791769.dkr.ecr.ap-south-1.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build Image
        env:
          REGISTRY: 767397791769.dkr.ecr.ap-south-1.amazonaws.com
          REPO: we-brokered
          REPOSITORY_TAG: ${REGISTRY}/${REPO}:${GITHUB_RUN_NUMBER}

        run: |
          docker build -t ${REPO} .
          docker tag ${REPO}:latest ${REGISTRY}/${REPO}:${GITHUB_RUN_NUMBER}
          docker push ${REGISTRY}/${REPO}:${GITHUB_RUN_NUMBER}
          docker system prune -af

  #--------------->

  deployToCluster:
    runs-on: self-hosted
    needs: buildImage-and-Push-to-ECR

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to EKS
        run: |
          sed -i "s|image: 767397791769.dkr.ecr.ap-south-1.amazonaws.com/we-brokered:.*|image: 767397791769.dkr.ecr.ap-south-1.amazonaws.com/we-brokered:$GITHUB_RUN_NUMBER|g" ./deployment.yaml
          kubectl apply -f ./deployment.yaml
